### PR TITLE
Fix #44 Allow generation of native launcher for products

### LINKED ISSUE #44: Wraps jars in Windows native executables
Is there any way to wraps (automatically) the output jar in a Windows *.EXE file. I am not very happy with the batch solution because of the visible command promp. 

Thanks in advance

### PR DESCRIPTION
**Pull request by ylemoigne**
Hi

Please, can you review my work on generation of native launcher. At this stage, it is not complete, but I would like to know if I'm on the good way and what refactor you would like to see before merging.

Note :
- windows launcher is ok (which was the primary request of issue #44 )
- OSX launcher in still a WIP (I don't understand why it don't work)
- I don't have a linux box under the hand to test it, I'll setup a VM this week end to check it out.

### CODE REVIEW

**Comment by ylemoigne** [comment]
Note change : 
 - OSX launcher is ok
 - Linux launcher is tested

**Comment by akhikhl** [comment]
Hi Yann,

Thanks a lot for your great contributions!

There were some little bugs, which I fixed:

1. issue #63: incorrect passing of jvmargs in EquinoxProductConfigurer.customizeIniFile.
2. issue #64: getEclipseBundleSymbolicName is invoked "too early" for rcp apps.
3. issue #65: EquinoxProductConfigurer generates eclipse.ini, although it should be ${project.name}.ini

please update your fork and do your tests/builds. If everything works with you, I'll make a release.

**Comment by ylemoigne** [comment]
As I said on twitter, It's a pleasure to try to improve Wuff.
 
I saw your fixes. Thanks to you for spotting 'my' bugs. Hard to think about all usecases.
I'll check with your version of the repository tomorrow evening and I come back to you.

**Comment by ylemoigne** [comment]
Nope there is problem. (I test your master + my pending PR). The "companion library" can't be found. The native counterpart of `org.equinox.launch` is not in plugins dir after product creation. I'll investigate tonight.

**Comment by akhikhl** [comment]
I just tried to reproduce this, without success.
Could you, please try:

```
git clone git@github.com:akhikhl/wuff.git
cd wuff
gradle build
cd examples/RcpApp-1/MyRcpApp
gradle build
```

Expected result: MyRcpApp/build/output/MyRcpApp-1.0.0.0-xxx/plugins contains unpacked org.eclipse.equinox.launcher with os-specific part (dll, so, ...).

**Comment by ylemoigne** [comment]
Ok, I reproduce my problem. If you add a name to the product :
products {
    product name: "foo", platform: 'windows', arch: 'x86_64'
}

Then the platform specific launcher is not there.

**Comment by ylemoigne** [comment]
I used the product name to build different "flavored" version. Maybe it was not intended for this usage.

If it's a correct usage, It seem there is a missmatch, in EquinoxProductConfigurer:60
configName = "${productConfigPrefix}${productNamePrefix}${platform}_${arch}${languageSuffix}"

And defaultConfig.groovy (which don't include productNamePrefix)

**Comment by akhikhl** [comment]
Good, I'll try that.

**Comment by akhikhl** [comment]
I confirm: adding "name" attribute removed native launcher. Will have a look.

**Comment by akhikhl** [comment]
I fixed the issue with native launchers and named products.
Could you, please, test the fix on snapshot?

**Comment by ylemoigne** [comment]
Good news. I made the test, it work for me :)

**Pull request merged**
